#!/bin/bash

ln -sf "$PWD/shell/profile" ~/.profile
ln -sf "$PWD/bash/config" ~/.bashrc
ln -sf "$PWD/bash/alias" ~/.bash/alias
ln -sf -T "$PWD/bash/apps" ~/.bash/apps
ln -sf -T "$PWD/bash/completion" ~/.bash/completion

ln -sf -T "$PWD/nvim" ~/.config/nvim
if [ -f "$PWD/git/local.config" ]; then
	ln -sf "$PWD/git/local.config" ~/.gitconfig.local
fi
ln -sf "$PWD/git/config" ~/.gitconfig
ln -sf "$PWD/tmux/config" ~/.tmux.conf

